title: Just a Log
author: zakklee
subtitle: Today I Learned, Roughly.

url: "https://jglee96.github.io/"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/rhl-bthr"
footer_text: "Theme by rhl-bthr"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   absolute-link: "https://www.linkedin.com/in/zakklee/"
